In [1]:
import sys, os, time

import open3d as o3d
import trimesh
import openmesh as om

import cv2

import scipy as sp
from scipy.sparse.linalg import eigs
from scipy.sparse import csr_matrix, identity
from scipy.sparse.linalg import spsolve

import numpy as np

import matplotlib.pyplot as plt

from tqdm import tqdm

%matplotlib inline

In [ ]:
# Tests of Openmesh
# https://gitlab.vci.rwth-aachen.de:9000/OpenMesh/openmesh-python/tree/master/tests

In [44]:
def read_mesh_om(path_in_models):
    return om.read_trimesh(os.path.join('..', 'models', path_in_models))
def write_mesh_om(mesh, path_in_models):
    om.write_mesh(os.path.join('..', 'models', path_in_models), mesh, vertex_color=True)
def show_mesh_o3d(plys):
    o3d.visualization.draw_geometries(plys)
def write_mesh_o3d(path, mesh):
    o3d.io.write_triangle_mesh(path, mesh)
def read_mesh_o3d(mesh_fp):
    return o3d.io.read_triangle_mesh(mesh_fp)

In [39]:
help(om.write_mesh)

Help on built-in function write_mesh in module openmesh:

write_mesh(...) method of builtins.PyCapsule instance
    write_mesh(*args, **kwargs)
    Overloaded function.
    
    1. write_mesh(filename: str, mesh: openmesh.TriMesh, binary: bool = False, msb: bool = False, lsb: bool = False, swap: bool = False, vertex_normal: bool = False, vertex_color: bool = False, vertex_tex_coord: bool = False, halfedge_tex_coord: bool = False, edge_color: bool = False, face_normal: bool = False, face_color: bool = False, color_alpha: bool = False, color_float: bool = False, status: bool = False, texture_file: str = '', material_file_extension: str = '.mat') -> None
    
    2. write_mesh(filename: str, mesh: openmesh.PolyMesh, binary: bool = False, msb: bool = False, lsb: bool = False, swap: bool = False, vertex_normal: bool = False, vertex_color: bool = False, vertex_tex_coord: bool = False, halfedge_tex_coord: bool = False, edge_color: bool = False, face_normal: bool = False, face_color: bool = Fa

In [32]:
mesh = read_mesh_om('cube.obj')

In [26]:
write_mesh_om(mesh, 'test/cube-copy.obj')

In [24]:
mesh.has_vertex_colors()

True

In [48]:
print(mesh.vertices())
set = False
for v_it in mesh.vertices():
    if not set:
        mesh.set_point(v_it, np.array([-1, -1 , 1]))
        set = True
    print(mesh.point(v_it), type(mesh.point(v_it)))
    print(v_it.idx())
    mesh.set_color(v_it, np.array([255.,182.,193.,255.])/255.)

# for f_it in mesh.faces():
#     mesh.set_color(f_it, np.array([255.,182.,193.,255.])/255.)
# for c_it in mesh.face_colors():
#     print(c_it, type(c_it))
write_mesh_om(mesh, 'test/cube-copy.off')

[-1. -1.  1.] <class 'numpy.ndarray'>
0
[ 0.5 -0.5  0.5] <class 'numpy.ndarray'>
1
[-0.5  0.5  0.5] <class 'numpy.ndarray'>
2
[0.5 0.5 0.5] <class 'numpy.ndarray'>
3
[-0.5  0.5 -0.5] <class 'numpy.ndarray'>
4
[ 0.5  0.5 -0.5] <class 'numpy.ndarray'>
5
[-0.5 -0.5 -0.5] <class 'numpy.ndarray'>
6
[ 0.5 -0.5 -0.5] <class 'numpy.ndarray'>
7


In [59]:
for f_it in mesh.faces():
    # help(f_it)
    for v_it in om.FaceVertexIter(mesh, f_it):
        print(mesh.point(v_it))
    print('--------')

[-1. -1.  1.]
[ 0.5 -0.5  0.5]
[-0.5  0.5  0.5]
--------
[-0.5  0.5  0.5]
[ 0.5 -0.5  0.5]
[0.5 0.5 0.5]
--------
[-0.5  0.5  0.5]
[0.5 0.5 0.5]
[-0.5  0.5 -0.5]
--------
[-0.5  0.5 -0.5]
[0.5 0.5 0.5]
[ 0.5  0.5 -0.5]
--------
[-0.5  0.5 -0.5]
[ 0.5  0.5 -0.5]
[-0.5 -0.5 -0.5]
--------
[-0.5 -0.5 -0.5]
[ 0.5  0.5 -0.5]
[ 0.5 -0.5 -0.5]
--------
[-0.5 -0.5 -0.5]
[ 0.5 -0.5 -0.5]
[-1. -1.  1.]
--------
[-1. -1.  1.]
[ 0.5 -0.5 -0.5]
[ 0.5 -0.5  0.5]
--------
[ 0.5 -0.5  0.5]
[ 0.5 -0.5 -0.5]
[0.5 0.5 0.5]
--------
[0.5 0.5 0.5]
[ 0.5 -0.5 -0.5]
[ 0.5  0.5 -0.5]
--------
[-0.5 -0.5 -0.5]
[-1. -1.  1.]
[-0.5  0.5 -0.5]
--------
[-0.5  0.5 -0.5]
[-1. -1.  1.]
[-0.5  0.5  0.5]
--------
